#!/bin/bash

ln -sf ~/bin/next-local ~/bin/next
ln -sf ~/bin/prev-local ~/bin/prev
ln -sf ~/bin/pp-local ~/bin/pp
ln -sf ~/bin/stop-local ~/bin/stop
ln -sf ~/bin/song-local ~/bin/song
ln -sf ~/bin/player-start-local ~/bin/player-start
