#!/bin/bash

# Display currently playing on remote mediaplayer
USER=mercury
IP=192.168.0.100

CURRENTLY_PLAYING=$(ssh ${USER}@${IP} "cmus-remote -C status | head -2 | tail -1 | tr -s '/' | cut -d' ' -f2- | cut -d'/' -f5-")

echo "~/$CURRENTLY_PLAYING"
notify-send "Currently playing" "~/$CURRENTLY_PLAYING"


